---
cache:
   job:
       main: [/main_job_cache]

shared:
  image: centos:8

jobs:
  main:
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 60
      screwdriver.cd/dockerEnabled: true

    steps:
      - set-x: set +x
      - try-podman: |
          yum install -y podman
          sed -i 's,"overlay","vfs",' /etc/containers/storage.conf
          podman --log-level=debug ps -a
          podman run  --net=host --events-backend=file  --cgroup-manager=cgroupfs --rm -ti --entrypoint bash vespaengine/vespa /opt/vespa/bin/vespa-start-configserver

      - try-docker: |
          ls -la /var/run/docker.sock
          exit 1

      - inspect: |
          cat /proc/cpuinfo
          cat /proc/meminfo
          df -h

          #docker --version
          #docker images
