---
shared:
  image: centos:8
  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
    screwdriver.cd/timeout: 60

jobs:
  test-docker:
    image: vespaengine/vespa-pipeline
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/dockerEnabled: true

    steps:
      - set-x: set -x
      - try-docker: |
          yum install -y yum-utils
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y docker-ce-cli
          export DOCKER_HOST="localhost:2375"
          docker system info
          ls -la $SD_DIND_SHARE_PATH
          mount
          df -h
          pwd

      - test: |
          cd $SD_DIND_SHARE_PATH

          yum install -y git
          git clone https://github.com/vespa-engine/documentation

          docker run --rm --net=host -e DOCKER_HOST -v $SD_DIND_SHARE_PATH:$SD_DIND_SHARE_PATH -w $SD_DIND_SHARE_PATH --entrypoint bash vespaengine/vespa -lc "pwd && ls -la && mount && ls -la / "

          #cd documentation
          #docker run --rm --net=host -e DOCKER_HOST -v $(pwd):/wd -w /wd --entrypoint /wd/travis/compile-and-test.sh vespaengine/vespa-pipeline
          #docker run --rm --net=host -e DOCKER_HOST -v $(pwd):/wd -w /wd --entrypoint bash vespaengine/vespa-pipeline -lc "ls -la /  && mount && ls -la /wd"
#      - test-copy: |
#          docker run -w /wd/documentation --rm -d --name testc --net=host -e DOCKER_HOST --init --entrypoint /usr/bin/tail vespaengine/vespa-pipeline -f /dev/null
#          docker cp $(pwd) testc:/wd
#          docker exec testc ls -la /wd
#          docker exec testc /wd/documentation/travis/compile-and-test.sh
#          docker stop testc
#          docker rm -f testc

  test-podman:
    #requires: [~pr, ~commit]
    steps:
      - set-x: set -x
      - try-podman: |
          dnf install -y podman
          sed -i 's,"overlay","vfs",' /etc/containers/storage.conf
          podman --log-level=debug ps -a
          podman run --net=host --events-backend=file --cgroup-manager=cgroupfs --rm docker.io/alpine cat /etc/alpine-release
          podman run --net=host --events-backend=file --cgroup-manager=cgroupfs --rm --entrypoint bash vespaengine/vespa /opt/vespa/bin/vespa-start-configserver
