---
shared:
  image: vespaengine/vespa-build-centos7

jobs:
  main:
    requires: [~pr, ~commit]
    annotations:
      screwdriver.cd/cpu: TURBO
      screwdriver.cd/ram: TURBO
      screwdriver.cd/disk: HIGH
      #screwdriver.cd/dockerEnabled: true
    steps:
      - inspect: |
          cat /proc/cpuinfo
          cat /proc/meminfo
          df -h
          #docker --version
          #docker images
      - checkout: |
          git clone --depth 1 https://github.com/vespa-engine/vespa
      - compile: |
          source /opt/rh/devtoolset-9/enable
          source /opt/rh/rh-maven35/enable
          cd vespa
          ./bootstrap.sh full
          cmake3 -DVESPA_UNPRIVILEGED=no -DVALGRIND_UNIT_TESTS=true -DVESPA_CPU_ARCH_FLAGS="-march=sandybridge -mtune=skylake" .
          make -j10
          make test ARGS="--output-on-failure -j $10"
          mvn --no-snapshot-updates --threads 1C -Dmaven.javadoc.skip=true -Dmaven.source.skip=true clean install

      - inspect-after: |
          df -h
